image: gcc
before_script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - apt-get install --yes libgtest-dev

stages:
  - test_style
  - build
  - test
  - test_extra

test_style:
  stage: test_style
  script:
    - ./linters/run.sh

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - "build"

test:
  stage: test
  script:
    - cd build
    - ctest -V -R Base

test_extra:
  stage: test_extra
  script:
    - cd build
    - ctest -V -R Extra
  when: manual
  allow_failure: false
